Corregir bug que impedía abrir declaraciones existentes
El trace back era el siguiente:
Traceback (most recent call last):
  File "/path/to/gdimm2/wndMain.py", line 223, in on_btnEditar_clicked
    vDeclaracion.update_container_from_xml()
  File "/path/to/gdimm2/wndDeclaracion.py", line 362, in update_container_from_xml
    if campo.text is None:
AttributeError: 'NoneType' object has no attribute 'text'